<?php

/**
 * AnalyticalTechniqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnalyticalTechniqueTable extends PluginAnalyticalTechniqueTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnalyticalTechniqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnalyticalTechnique');
    }
}