<?php

/**
 * ConfigurationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigurationsTable extends PluginConfigurationsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigurationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Configurations');
    }
}