<?php

/**
 * ContactAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactAddressTable extends PluginContactAddressTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactAddress');
    }
}