<?php

/**
 * DenominationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DenominationTable extends PluginDenominationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DenominationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Denomination');
    }
}