<?php

/**
 * DenominationsGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DenominationsGroupTable extends PluginDenominationsGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DenominationsGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DenominationsGroup');
    }
}