<?php

/**
 * DeterminationTypeMethodConstantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeterminationTypeMethodConstantTable extends PluginDeterminationTypeMethodConstantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeterminationTypeMethodConstantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeterminationTypeMethodConstant');
    }
}