<?php

/**
 * DeterminationTypeFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeterminationTypeFieldTable extends PluginDeterminationTypeFieldTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeterminationTypeFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeterminationTypeField');
    }
}