<?php

/**
 * DeterminationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeterminationStatusTable extends PluginDeterminationStatusTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeterminationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeterminationStatus');
    }
}