<?php

/**
 * DeterminationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeterminationTable extends PluginDeterminationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeterminationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Determination');
    }
}