<?php

/**
 * LabTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabTable extends PluginLabTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lab');
    }
}