<?php

/**
 * LimitsGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LimitsGroupTable extends PluginLimitsGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LimitsGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LimitsGroup');
    }
}