<?php

/**
 * LimitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LimitTable extends PluginLimitTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LimitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Limit');
    }
}