<?php

/**
 * MatrixTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatrixTable extends PluginMatrixTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatrixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Matrix');
    }
}