<?php

/**
 * MethodDenomination
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Labber
 * @subpackage model
 * @author     LiberSoft <info@libersoft.it>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MethodDenomination extends PluginMethodDenomination
{
}
