<?php

/**
 * MethodMethodConstantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodMethodConstantTable extends PluginMethodMethodConstantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MethodMethodConstantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodMethodConstant');
    }
}