<?php

/**
 * MethodRuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodRuleTable extends PluginMethodRuleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MethodRuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodRule');
    }
}