<?php

/**
 * MethodConstantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodConstantTable extends PluginMethodConstantTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MethodConstantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodConstant');
    }
}