<?php

/**
 * MethodMatrixTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodMatrixTable extends PluginMethodMatrixTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MethodMatrixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodMatrix');
    }
}