<?php

/**
 * MethodFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodFileTable extends PluginMethodFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MethodFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodFile');
    }
}