<?php

/**
 * MethodUnitOfMeasurementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodUnitOfMeasurementTable extends PluginMethodUnitOfMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MethodUnitOfMeasurementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodUnitOfMeasurement');
    }
}