<?php

/**
 * MethodReportColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodReportColumnTable extends PluginMethodReportColumnTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MethodReportColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodReportColumn');
    }
}