<?php

/**
 * OfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfferTable extends PluginOfferTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer');
    }
}