<?php

/**
 * OfferSectionSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfferSectionSourceTable extends PluginOfferSectionSourceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfferSectionSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OfferSectionSource');
    }
}