<?php

/**
 * OfferSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfferSectionTable extends PluginOfferSectionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfferSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OfferSection');
    }
}