<?php

/**
 * PacketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacketTable extends PluginPacketTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Packet');
    }
}