<?php

/**
 * ReportColumnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportColumnTable extends PluginReportColumnTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportColumnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReportColumn');
    }
}