<?php

/**
 * SampleFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SampleFileTable extends PluginSampleFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SampleFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SampleFile');
    }
}