<?php

/**
 * SampleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SampleTable extends PluginSampleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SampleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sample');
    }
}