<?php

/**
 * UnitOfMeasurementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitOfMeasurementTable extends PluginUnitOfMeasurementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitOfMeasurementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitOfMeasurement');
    }
}