<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginOffer extends BaseOffer
{
  public function preUpdate($event)
  {
    foreach ($this->getModified() as $k => $v)
    {
      switch ($k)
      {
        case 'revision_number':
          $this->updateHistory('Revisione', $v);
          break;
      }
    }
  }

  public function updateHistory($action, $value)
  {
    $history = json_decode($this->history);
    $history[] = array(
      'user' => sfContext::getInstance()->getUser()->getGuardUser()->username,
      'action' => $action,
      'value' => $value,
      'timestamp' => time(),
    );
    $this->setHistory(json_encode($history));
  }

  /**
   * Setta il numero progressivo dell'offerta.
   *
   * @param type $event
   */
  public function postInsert($event)
  {
    // TODO: una cosa vera.
    $this->setNumber(time());
    $this->save();
  }
}
