<?php

/**
 * OfferSectionSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * TODO: use PHP 5.4 traits!
 * 
 * @package    lsLabberPlugins
 * @subpackage model
 * @author     LiberSoft <info@libersoft.it>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginOfferSectionSource extends BaseOfferSectionSource
{
  public function getSource()
  {
    return $this->determination_id ? 'Controllo' : 'Pacchetto';
  }

  public function getName()
  {
    return $this->determination_id ? $this->Determination->Denomination->name : $this->Packet->name;
  }

  public function getCost()
  {
    return $this->determination_id ? $this->Determination->price : $this->Packet->price;
  }

  public function getDescription()
  {
    if ($this->isPacket())
    {
      $denominations = array();

      foreach ($this->Packet->Determinations as $determination)
      {
        $denominations[] = $determination->Denomination->name;
      }

      return implode(', ', $denominations);
    }
    else
    {
      return '';
    }
  }

  public function getMethod()
  {
    if (!$this->isPacket())
    {
      return $this->Determination->Method->name;
    }
    else
    {
      return '';
    }
  }

  public function isPacket()
  {
    return (bool) $this->packet_id;
  }

  public function getDeterminations()
  {
    if ($this->isPacket())
    {
      return $this->Packet->Determinations;
    }
    else
    {
      return array();
    }
  }

  public function toPriceArray()
  {
    return array(
      'id'     => $this->id,
      'name'   => $this->getName(),
      'source' => $this->getSource(),
      'cost'   => $this->getCost(),
      'price'  => $this->price,
    );
  }

  public function postInsert($event)
  {
    if ($this->price === null)
    {
      $multiplier = Doctrine::getTable('Configurations')->findOneBy('name', 'price_multiplier');
      $this->setPrice($this->getCost() * floatval($multiplier->value));
      $this->save();
    }
  }
}
