<?php

/**
 * PluginConfigurationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginConfigurationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginConfigurationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginConfigurations');
    }
}