<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMatrix extends BaseMatrix
{
  public function getAssociatedMethods()
  {
    $csl = '';

    foreach ($this->getMethodMatrix() as $i => $mm)
    {
      $csl .= ($i != 0) ? ', ' . $mm->getMethod() : $mm->getMethod();
    }

    return $csl;
  }

  public function getParentIds()
  {
    if ($this->parent_id)
    {
      $tree[] = $this->parent_id;
      $tree = array_merge($tree, $this->getParent()->getParentIds());
    }
    else
    {
      $tree = array();
    }

    return $tree;
  }

  public function getChildIds()
  {
    foreach ($this->getSubmatrices() as $child)
    {
      $tree[] = $child->id;

      if ($child->hasChildren())
      {
        $tree = array_merge($tree, $child->getChildIds());
      }
    }

    return $tree;
  }

  public function hasChildren()
  {
    return $this->getSubmatrices()->count();
  }
}