<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginDeterminationTable extends Doctrine_Table
{
  public function getLabDeterminations()
  {
    $q = $this->createQuery('d')
      ->leftJoin('d.Method.Unit u')
      ->leftJoin('d.Matrix')
      ->leftJoin('d.Denomination')
      ->leftJoin('d.Scale')
      ->leftJoin('d.UnitOfMeasurement')
      ->leftJoin('d.Sample.Order.Contact')
      ->where('d.sample_id is not null')
      ->andWhere('d.Sample.bozza = ?', 0);

    return $q;
  }
}
