<?php

/**
 * Order
 * 
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 * 
 * @package    phonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginOrder extends BaseOrder
{
  public function postInsert($event)
  {
    $this->setNumero('bozza-'.$this->id);
    $this->save();
  }

  public function sbozza()
  {
    if ($this->bozza)
    {
      $this->setNumero(OrderTable::nextInternalNumber());
      $this->setBozza(false);

      if ($this->accepted_at == null)
      {
        $this->setAcceptedAt(date('Y-m-d H:i:s'));
      }

      $guardUser = sfContext::getInstance()->getUser()->getGuardUser();

      $history = json_decode($this->storico);
      $history[] = array(
        'user_id' => $guardUser->id,
        'action' => 'accepted',
        'value' => true,
        'timestamp' => time(),
      );
      $this->set('storico', json_encode($history));

      $this->save();
    }

    foreach ($this->getSamples() as $sample)
    {
      $sample->sbozza();
    }
  }

  /**
   * Altrimenti non cancella i Sample collegati.
   *
   * @param type $event
   */
  public function preDelete($event)
  {
    Doctrine_Manager::getInstance()->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, false);
  }
}
