<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUserTable extends Doctrine_Table
{
  public function retrieveSalesManagersList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->andWhere($rootAlias . '.in_sales = ?', true)
      ->orderBy($rootAlias . '.surname');

    return $q;
  }

  public function retrieveSalesSecretaryList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->andWhere($rootAlias . '.is_sales_secretary = ?', true)
      ->orderBy($rootAlias . '.surname');
    return $q;
  }

  public function retrieveTechnicalManagerList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->andWhere($rootAlias . '.is_technical_manager = ?', true)
      ->orderBy($rootAlias . '.surname');
    return $q;
  }

}