<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMethodFieldTable extends Doctrine_Table
{
  public function retrieveMethodFieldsList(Doctrine_Query $q)
	{
    $objectId = sfContext::getInstance()->getRequest()->getParameter('objectId');

		$rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.FieldType f')
      ->where($rootAlias . '.method_id = ?', $objectId);
    return $q;
	}
}