<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginDepartmentTable extends Doctrine_Table
{
  public static function checkAssociation()
  {
    $departments = Doctrine::getTable('Department')->findAll();

    foreach ($departments as $department)
    {
      if ($department->hasUnassociatedSampleTypes())
      {
        return true;
      }
    }

    return false;
  }
}