<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUnitOfMeasurement extends BaseUnitOfMeasurement
{

  public function __toString(){
    return $this->getName() . ' (' . $this->getSymbol() . ')';
  }

}