<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSIPrefix extends BaseSIPrefix
{

  public function __toString(){
    return $this->getName() . ' (' . $this->getPrefix() . ')';
  }

}