<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginDenominationTable extends Doctrine_Table
{
  public function filterByBranch(Doctrine_Query $q, $rootId)
  {
    $rootAlias = $q->getRootAlias();

    $root = Doctrine::getTable('Matrix')->find($rootId);
    $tree = $root->getChildIds();

    $q->leftJoin($rootAlias . '.DeterminationType dt')
      ->andWhereIn('dt.matrix_id', $tree);

    return $q;
  }
}