<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginOfferSection extends BaseOfferSection
{
  public function postInsert($event)
  {
    $q = Doctrine_Query::create()
      ->from('OfferSection os')
      ->where('os.offer_id = ?', $this->offer_id);

    $this->section_number = $q->count();
    $this->save();
  }

  public function preUpdate($event)
  {
    if (!$this->offered_price)
    {
      $this->offered_price = $this->price;
    }
  }
}
