<?php

/**
 * PluginBillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBill');
    }
}