<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMethodConstantTable extends Doctrine_Table
{
  public function retrieveMethodConstantList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Department d');

    // FIXME: (un giorno) niente sfContext nel mio modello.
    $user = sfContext::getInstance()->getUser();

    if ($user->isInterdepartmental())
    {
      return $q;
    }

    $departmentId = $user->getProfile()->getDepartmentId();
    return $q->andWhere($rootAlias. '.department_id = ?', $departmentId);
  }
}