<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMethodTable extends Doctrine_Table
{
  public function retrieveWithDeterminationTypes(Doctrine_Query $q, $matrixId)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.DeterminationType dt')
      ->leftJoin('dt.Denomination d')
//      ->leftJoin('dt.Fields f')
//      ->leftJoin('f.FieldType ft')
      ->andWhere('dt.matrix_id = ?', $matrixId);

    return $q;
  }

  public function filterByBranch(Doctrine_Query $q, $rootId)
  {
    $rootAlias = $q->getRootAlias();

    $root = Doctrine::getTable('Matrix')->find($rootId);
    $tree = $root->getChildIds();

    $q->leftJoin($rootAlias . '.DeterminationType dt')
      ->andWhereIn('dt.matrix_id', $tree);

    return $q;
  }

  public function retrieveMethodsList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Department d')
      ->leftJoin($rootAlias . '.Organization o');

    // FIXME: (un giorno) niente sfContext nel mio modello.
    $user = sfContext::getInstance()->getUser();

    if ($user->isInterdepartmental())
    {
      return $q;
    }

    $departmentId = $user->getProfile()->getDepartmentId();
    return $q->andWhere($rootAlias. '.department_id = ?', $departmentId);
  }
}