<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMethodRuleTable extends Doctrine_Table
{
  public function retrieveMethodRulesList(Doctrine_Query $q)
	{
    $objectId = sfContext::getInstance()->getRequest()->getParameter('objectId');

		$rootAlias = $q->getRootAlias();
    $q->where($rootAlias . '.method_id = ?', $objectId);
    return $q;
	}
}