<?php

/**
 * RdpTable
 * 
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginRdpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RdpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rdp');
    }
}