<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginDeterminationTypeTable extends Doctrine_Table
{

  public function retrieveDeterminationType(Doctrine_Query $q)
  {
    $objectId = sfContext::getInstance()->getRequest()->getParameter('objectId');
		$rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Method f')
      ->leftJoin($rootAlias . '.Denomination d')
      ->leftJoin($rootAlias . '.Matrix e')
      ->leftJoin($rootAlias . '.Fields ff')
      ->leftJoin($rootAlias . '.Fields.FieldType ft')
      ->where($rootAlias . '.method_id = ?', $objectId);
    return $q;
	}

}