<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMethodMatrixTable extends Doctrine_Table
{
  public function retrieveMethodMatrixesList(Doctrine_Query $q)
	{
    $objectId = sfContext::getInstance()->getRequest()->getParameter('objectId');

		$rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Matrix m')
      ->where($rootAlias . '.method_id = ?', $objectId)
      ->orderBy('m.name');
    return $q;
	}
}