<?php

/**
 * PluginSampleSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSampleSourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSampleSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSampleSource');
    }
}