<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginOrganization extends BaseOrganization
{

  public function __toString(){
    return $this->getShortName();
  }

}