<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMethodField extends BaseMethodField
{

  public function getName(){
    return $this->getFieldType()->getName();
  }

}