<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPacket extends BasePacket
{
  /**
   * Copia le Determination di un Packet e le assegna a un altro
   * Packet o a un Sample, in base al primo parametro
   *
   * @param $local può essere packet_id o sample_id
   * @param $id è l'id del nuovo oggetto al quale associare la Determination
   * @param $pdp è il nome del pacchetto "contenitore"
   */
  public function copyDeterminations($local, $id, $pdp = null)
  {
    foreach ($this->getDeterminations() as $determination)
    {
      $determinationCopy = $determination->copy();
      $determinationCopy->set('packet_id', null);
      $determinationCopy->set($local, $id);
      $determinationCopy->set('origine', $this->name);
      $determinationCopy->set('rdp_title', $this->report_title);
      $determinationCopy->set('pdp', $pdp);

      // Setta il JSON 'source' per l'indicazione dell'origine di
      // questa Determination ai fini della fatturazione, solo se
      // assegnata ad un Sample
      if ($local === 'sample_id')
      {
        $source = array(
          'table' => 'Packet',
          'id'    => $this->id
        );
        $determinationCopy->set('source', json_encode($source));
      }

      // Imposta la "Data inizio" del controllo nel campione ad oggi
      if ($local == 'sample_id')
      {
        $determinationCopy->set('data_inizio', date('Y-m-d', time()));
      }

      $determinationCopy->set('created_at', date('Y-m-d h:i:s', time()));
      $determinationCopy->set('updated_at', date('Y-m-d h:i:s', time()));
      $determinationCopy->save();
    }

    // Associa sezione di offerta al Packet in OfferSectionSource
    if ($local === 'offer_section_id')
    {
      $source = new OfferSectionSource();
      $source->offer_section_id = $id;
      $source->packet_id = $this->id;
      $source->save();
    }
  }
}
