<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPacketTable extends Doctrine_Table
{
  public function retrieveProtoPacketList(Doctrine_Query $q, $matrixId = null)
  {
    $rootAlias = $q->getRootAlias();

    // TODO: filtrare per coerenza con matrixId
    $q->andWhere('is_proto = 1');

    return $q;
  }

  public function retrieveOtherPacketsList(Doctrine_Query $q)
	{
    $objectId = sfContext::getInstance()->getRequest()->getParameter('objectId');

		$rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Matrix m')
      ->where('id != ?', $objectId);
    return $q;
	}
}