<?php

/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUser extends BaseUser
{
    public function __toString(){
        return $this->name . ' ' . $this->surname;
    }

}