<?php

/**
 * PluginSampleFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSampleFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSampleFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSampleFile');
    }
}