<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMatrixTable extends Doctrine_Table
{
  public function retrieveRootMatricesList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->andWhere($rootAlias . '.parent_id IS NULL')
      ->addOrderBy($rootAlias . '.department_id')
      ->addOrderBy($rootAlias . '.name');

    return $q;
  }

  public function retrieveMatrixBranch(Doctrine_Query $q, $rootId = null)
  {
    if ($rootId)
    {
      $rootAlias = $q->getRootAlias();

      $root = Doctrine::getTable('Matrix')->find($rootId);
      $tree = $root->getChildIds();

      return $q->andWhereIn($rootAlias . '.id', $tree);
    }
    else
    {
      return $q;
    }
  }

  public static function getRoots()
  {
    $q = Doctrine_Core::getTable('Matrix')
      ->createQuery('m')
      ->where('m.parent_id is null')
      ->orderBy('m.name');

    return $q->execute();
  }

  static public $categories = array(
    'matrix'      => 'Matrici',
    'composition' => 'Composizione',
    'state'       => 'Stato',
    'destination' => 'Destinazione'
  );

  public function getCategories()
  {
    return self::$categories;
  }

  public function retrieveMatrixesList(Doctrine_Query $q, $only_roots = false)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.Department d')
      ->leftJoin($rootAlias . '.ParentMatrix pm')
      ->leftJoin($rootAlias . '.ChildMatrix cm')
      ->orderBy('name');

    if ($only_roots)
    {
      $q->andWhere($rootAlias . '.id NOT IN (SELECT matrix_id as id FROM MatrixMatrix mm ORDER BY matrix_id)');
    }

    // FIXME: (un giorno) niente sfContext nel mio modello.
    $user = sfContext::getInstance()->getUser();

    if ($user->isInterdepartmental())
    {
      return $q;
    }

    $departmentId = $user->getProfile()->getDepartmentId();
    return $q->andWhere($rootAlias. '.department_id = ?', $departmentId);
  }
}
