<?php

/**
 * OfferSectionSourceTable
 * 
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginOfferSectionSourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfferSectionSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OfferSectionSource');
    }
}