<?php

/**
 * PacketPacket
 * 
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pHonline
 * @subpackage model
 * @author     LiberSoft <info@libersoft.it>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPacketPacket extends BasePacketPacket
{
}
