<?php

/**
 * PluginAnalyticalTechniqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnalyticalTechniqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAnalyticalTechniqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAnalyticalTechnique');
    }
}