<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginOfferTable extends Doctrine_Table
{
  public function retrieveTemplateList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Contact c')
      ->where('is_template = ?', true);
    return $q;
  }

  public function retrieveOfferList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Contact c')
      ->leftJoin($rootAlias . '.SalesManager sm')
      ->leftJoin($rootAlias . '.SalesSecretary ss')
      ->leftJoin($rootAlias . '.TechnicalManager tm')
      ->andWhere('is_template = ?', false);
    return $q;
  }

  public function retrieveActiveOffersList(Doctrine_Query $q)
  {
    return $q->andWhereNotIn('offer_state', array(3, 4));
  }
}
