<?php
/**
 * This abstract class Pluginhas been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUnitOfMeasurementTable extends Doctrine_Table
{
  public function retrieveAssociatedWithMethod(Doctrine_Query $q, $methodId)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.AssociatedMethods am')
      ->andWhere('am.id = ?', $methodId);

    return $q;
  }
}